// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from '@/utils/ajax';

/**
* Get charge orders
*/
export async function ChargeOrderControllerFindAll(
  params: Paths.ChargeOrderControllerFindAll.BodyParameters,
): Promise<{
    error: string;
    data: Paths.ChargeOrderControllerFindAll.Responses
}> {
  // /v1/charge-order
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.get(`/v1/charge-order`,  {
    params: _params
  });
}

/**
* 
*/
export async function ChargeOrderControllerFindById(
  params: Paths.ChargeOrderControllerFindById.BodyParameters,
): Promise<{
    error: string;
    data: Definitions.ChargeOrderDto
}> {
  // /v1/charge-order/{id}
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.get(`/v1/charge-order/${_params.id}`,  {
    params: _params
  });
}

