// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from '@/utils/ajax';

/**
* Get users
*/
export async function ClerkControllerFindAll(
  params: Paths.ClerkControllerFindAll.BodyParameters,
): Promise<{
    error: string;
    data: Paths.ClerkControllerFindAll.Responses
}> {
  // /v1/clerk
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.get(`/v1/clerk`,  {
    params: _params
  });
}

