// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from '@/utils/ajax';

/**
* Get gift codes
*/
export async function GiftCodeControllerFindAll(
  params: Paths.GiftCodeControllerFindAll.BodyParameters,
): Promise<{
    error: string;
    data: Paths.GiftCodeControllerFindAll.Responses
}> {
  // /v1/gift-code
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.get(`/v1/gift-code`,  {
    params: _params
  });
}

/**
* Create gift code
*/
export async function GiftCodeControllerCreate(
  params: Definitions.GiftCodeCreateDto,
): Promise<{
    error: string;
    data: Definitions.GiftCodeDto
}> {
  // /v1/gift-code
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.post(`/v1/gift-code`,  {
    ..._params
  });
}

/**
* Update gift code
*/
export async function GiftCodeControllerUpdate(
  params: Definitions.GiftCodeUpdateDto,
): Promise<{
    error: string;
    data: Definitions.GiftCodeDto
}> {
  // /v1/gift-code/{id}
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.put(`/v1/gift-code/${_params.id}`,  {
    ..._params
  });
}

/**
* Delete gift code
*/
export async function GiftCodeControllerDelete(
  params: Paths.GiftCodeControllerDelete.BodyParameters,
): Promise<{
    error: string;
    data: Paths.GiftCodeControllerDelete.Responses
}> {
  // /v1/gift-code/{id}
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.delete(`/v1/gift-code/${_params.id}`,  {
    ..._params
  });
}

