// @ts-ignore
/* eslint-disable */
///////////////////////////////////////////////////////////////////////
//                                                                   //
// this file is autogenerated by service-generate                    //
// do not edit this file manually                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
/// <reference path = "api-auto.d.ts" />
import request from '@/utils/ajax';

/**
* Get memory heap status
*/
export async function HealthPublicControllerCheckMemoryHeap(
  params: Paths.HealthPublicControllerCheckMemoryHeap.BodyParameters,
): Promise<{
    error: string;
    data: Definitions.HealthSerialization
}> {
  // /health/memory-heap
  let _params: { [key: string]: any } = {
    ...params,
  };
  return request.get(`/health/memory-heap`,  {
    params: _params
  });
}

